# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: nrfmicro_13_52833
    shield: corne_left
  - board: nrfmicro_13_52833
    shield: corne_right
  - board: nrfmicro_13_52833
    shield: jorne_left
  - board: nrfmicro_13_52833
    shield: jorne_right
  - board: nrfmicro_13_52833
    shield: jiran_left
  - board: nrfmicro_13_52833
    shield: jiran_right
  - board: nrfmicro_13_52833
    shield: lily58_left
  - board: nrfmicro_13_52833
    shield: lily58_right