manifest:
  remotes:
    - name: krikun98
      url-base: github.com/krikun98/zmk
  projects:
    - name: zmk
      remote: krikun98
      revision: main
      import: app/west.yml
  self:
    path: config
