manifest:
  remotes:
    - name: joric
      url-base: https://github.com/joric
  projects:
    - name: zmk
      remote: joric
      revision: jorne
      import: app/west.yml
  self:
    path: config