manifest:
  remotes:
    - name: krikun98
      url-base: https://github.com/krikun98
  projects:
    - name: zmk
      remote: krikun98
      revision: main
      import: app/west.yml
  self:
    path: config
